### ISSUE TITLE
gridmet temp data for Feb 1 2015 around 0 K

### ISSUE THREAD

**Issue by bdaudert** [Google-Drought/WebInterface#95] opened 2015-02-16 15:57 UTC
gridmet temp data for Feb 1 2015 are messed up across the US. Look at the time series output

http://drought-monitor3.appspot.com/?minColorbar=-20&anomOrValue=value&dateStart=2014-12-18&SWLat=40.0&p4check=checked&p2display=none&SWLong=-111.0&yearEndClim=2010&p4=-112.7471,42.0897&pointsLongLat=-119.8003,39.5207&opacity=0.7&p5=-112.7471,42.0897&p7check=checked&p1check=checked&p6display=none&domainType=points&mapzoom=6&NELat=45.0&p3check=checked&varUnits=deg%20C&p2check=checked&marker_colors=[%27blue%27,%20%27green%27,%20%27orange%27,%20%27purple%27,%20%27yellow%27,%20%27pink%27,%20%27red%27]&colorbarLabel=Mean%20Temperature%20(deg%20C)&chartType=column&mapid=80ea844f8018d93db1c8d45a6adc3989&p7display=none&colorbarsize=8&p6=-112.7471,42.0897&p1=-119.8003,39.5207&kmloption=&p3=-112.7471,42.0897&maxYear=2015&yearEnd=2015&p5display=none&colorbarmap=BuRd&token=d76885908db2fb1cbab0d38900333057&p7=-112.7471,42.0897&units=metric&p1display=block&layer=none&timeSeriesCalc=days&p2=-112.7471,42.0897&maxColorbar=20&yearStart=1979&yearStartClim=1979&p4display=none&maxDate=2015-02-14&state=California&palette=2166ac,4393c3,92c5de,d1e5f0,fddbc7,f4a582,d6604d,b2182b&variable=Gtmean&p3display=none&minDate=1979-01-01&statistic=Mean&dateEnd=2015-02-14&minYear=1979&p6check=checked&p5check=checked&mapCenterLongLat=-112.7471,42.0897&NELong=-95.0&kmlurl=

**Comment by cgmorton** [comment] 2015-02-16 18:21
I think this is a duplicate of issue 88 that Katherine already mentioned to John.

**Closed** 2015-02-16 19:02 UTC
Labels: bug
