### ISSUE TITLE
HUC boundaries also show climate divison layers

### ISSUE THREAD

**Issue by cgmorton** [Google-Drought/WebInterface#80] opened 2015-02-07 00:48 UTC
On the hangout Justin was showing MODIS anomalies and the climate division layers were being drawn with the HUC boundaries even though HUC was selected.

**Comment by cgmorton** [comment] 2015-02-09 17:52
Seems to be triggering when I switch to a climatology

**Comment by khegewisch** [comment] 2015-02-09 19:23
Charles, can you describe an exact set of parameters that leads to this error? I cannot reproduce it. 

k

**Comment by cgmorton** [comment] 2015-02-09 19:23
To reproduce:
Go to http://drought-monitor3.appspot.com/
Change to MODIS NDVI (Vegetation Index)
Click "GET MAP"
In "Map Options" select "US Hydrologic Unit Code(HUC) Layer"
Change "Values" to "Climatology"
Click "GET MAP"
You should see HUCS and Climate Division Layers?

**Comment by khegewisch** [comment] 2015-02-09 21:54
In template/includes/js_overlays.html, 

the climate divs selection actually said 
if layer=='hucoverlay' instead of 'climatedivoverlay'

fixed now.

**Closed** 2015-02-09 21:54 UTC
